// --------------------------------------------------------------------
// <auto-generated>
// This is a CDP xPlat pipeline generated file for managed C# projects.
// </auto-generated>
// --------------------------------------------------------------------

using System.Reflection;
[assembly: AssemblyVersion("0.0.02959.1")]
[assembly: AssemblyFileVersion("0.0.02959.1")]
[assembly: AssemblyInformationalVersion("0.0.02959.1")]