// --------------------------------------------------------------------
// <auto-generated>
// This is a CDP xPlat pipeline generated file for native projects.
// </auto-generated>
// --------------------------------------------------------------------

#define ASSEMBLY_VERSION "0.0.02959.1"
#define ASSEMBLY_FILE_VERSION "0.0.02959.1"
#define ASSEMBLY_INFORMATIONAL_VERSION "0.0.02959.1"
